### ISSUE TITLE
[BUG] Incorrect time recorded for chat messages

### ISSUE THREAD

**Issue by morganedmonds** [willowtreeapps/wombats-web-client#108]
The time recorded is 5 hours ahead, presumably set at UTC.

**Comment by oconn** [comment]
This appears to have been addressed when the API was refactored to use UTC timestamps

**Comment by morganedmonds** [comment]
@oconn I'm still seeing incorrect time stamps. See below. Moving back to ready.
<img width="908" alt="screen shot 2017-02-21 at 10 15 15 am" src="https://cloud.githubusercontent.com/assets/25081733/23170853/b759dd12-f81e-11e6-869b-8730146771fe.png">

**Comment by morganedmonds** [comment]
this looks good! i also checked to make sure the time was correct for a user in a different time zone.
